package com.roncoo.eshop.cache.model;

import lombok.Data;

import java.util.Date;

@Data
public class ShopInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.good_comment_rate
     *
     * @mbg.generated
     */
    private Double goodCommentRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.id
     *
     * @return the value of shop_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.id
     *
     * @param id the value for shop_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.name
     *
     * @return the value of shop_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.name
     *
     * @param name the value for shop_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.level
     *
     * @return the value of shop_info.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.level
     *
     * @param level the value for shop_info.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.good_comment_rate
     *
     * @return the value of shop_info.good_comment_rate
     *
     * @mbg.generated
     */
    public Double getGoodCommentRate() {
        return goodCommentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.good_comment_rate
     *
     * @param goodCommentRate the value for shop_info.good_comment_rate
     *
     * @mbg.generated
     */
    public void setGoodCommentRate(Double goodCommentRate) {
        this.goodCommentRate = goodCommentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.create_time
     *
     * @return the value of shop_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.create_time
     *
     * @param createTime the value for shop_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.update_time
     *
     * @return the value of shop_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.update_time
     *
     * @param updateTime the value for shop_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}